// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/carpets" | "/admin/carpets/create" | "/admin/carpets/restock" | "/admin/categories" | "/admin/discounts" | "/admin/orders" | "/admin/prices" | "/admin/promocodes" | "/admin/users" | "/auth/google/callback" | "/carpets" | "/carpets/[id]" | "/cart" | "/checkout" | "/contact" | "/forgot-password" | "/joynamozlar" | "/login" | "/mashhur-gilamlar" | "/orders" | "/orders/[id]" | "/ovalni-gilamlar" | "/profile" | "/register" | "/reset-password" | "/turlar" | "/turlar/[id]" | "/yangi-gilamlar"
type AppRouteHandlerRoutes = "/api/v1/[...path]" | "/uploads/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/carpets": {}
  "/admin/carpets/create": {}
  "/admin/carpets/restock": {}
  "/admin/categories": {}
  "/admin/discounts": {}
  "/admin/orders": {}
  "/admin/prices": {}
  "/admin/promocodes": {}
  "/admin/users": {}
  "/api/v1/[...path]": { "path": string[]; }
  "/auth/google/callback": {}
  "/carpets": {}
  "/carpets/[id]": { "id": string; }
  "/cart": {}
  "/checkout": {}
  "/contact": {}
  "/forgot-password": {}
  "/joynamozlar": {}
  "/login": {}
  "/mashhur-gilamlar": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/ovalni-gilamlar": {}
  "/profile": {}
  "/register": {}
  "/reset-password": {}
  "/turlar": {}
  "/turlar/[id]": { "id": string; }
  "/uploads/[...path]": { "path": string[]; }
  "/yangi-gilamlar": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
